### ISSUE TITLE
Can't find your paper.pdf, through Google.

### ISSUE THREAD

**Issue by justopit** [LuckyDC/generalizing-reid#1]
Thanks to the code. However, I can't find your paper pdf using Google. Can you give me a link to your paper?Google Cloud?Or BaiDu WanPang?

**Comment by LuckyDC** [comment]
ECCV has released the open access of accepted papers. You can download our paper from https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123600222.pdf
